name: development environment continuous integration

on: 
  schedule:
    - cron: '0 8 * * *' # run at 8 AM UTC (12 am PST)
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pestpp-devenv:
    name: developer environment
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          #- {os: macos-latest, shell: bash}
          - {os: macos-14, shell: bash}
          - {os: ubuntu-latest, shell: bash}
          - {os: ubuntu-22.04, shell: bash}
          - {os: windows-latest, shell: bash}
    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
      - uses: actions/checkout@v5

      - uses: prefix-dev/setup-pixi@v0.9.2
        with:
          pixi-version: v0.58.0
          manifest-path: "pixi.toml"

      # - name: Install modflow
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     pixi run install-modflow
  
      - name: Build release
        run: pixi run build-release 

      # - name: Test pestpp
      #   run: |
      #     pixi run test

      - name: Upload binaries
        uses: actions/upload-artifact@v5
        with:
          name: binaries-${{ matrix.os }}
          path: bin
            
      - name: Upload test results
        uses: actions/upload-artifact@v5
        with:
          name: test-results-${{ matrix.os }}
          path: benchmarks/large_fake_test/master
